In [1]:
!pip3 install numpy


[notice] A new release of pip available: 22.3.1 -> 23.1.2
[notice] To update, run: pip3 install --upgrade pip


In [2]:
import numpy as np

In [3]:
a = np.arange(6)

In [4]:
type(a)

numpy.ndarray

In [5]:
a

array([0, 1, 2, 3, 4, 5])

In [6]:
a[0]

0

In [7]:
a[1]

1

In [8]:
a[:]

array([0, 1, 2, 3, 4, 5])

In [9]:
a2 = a[np.newaxis, :]

In [10]:
a2

array([[0, 1, 2, 3, 4, 5]])

In [11]:
a2.shape

(1, 6)

In [12]:
a.shape

(6,)

In [14]:
a = np.array([[1,2,3,4],[5,6,7,8,],[9,10,11,12]])

In [15]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [16]:
a[0,1]

2

In [17]:
a[0]

array([1, 2, 3, 4])

In [18]:
a[1]

array([5, 6, 7, 8])

In [19]:
a[2]

array([ 9, 10, 11, 12])

In [20]:
a = np.array([1,2,3])

In [21]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [22]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [23]:
np.empty(2)

array([2.05833592e-312, 2.33419537e-312])

In [26]:
np.arange(2,9,2)

array([2, 4, 6, 8])

In [27]:
np.linspace(0,10,num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [33]:
b = np.ones(2, dtype=np.int64)

In [34]:
b

array([1, 1])

In [35]:
arr = np.array ([2, 1, 5, 3, 7, 4, 6, 8])

In [36]:
arr

array([2, 1, 5, 3, 7, 4, 6, 8])

In [40]:
arr = np.sort(arr)

In [41]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [42]:
a = ([1,2,3,4])
b = ([5,6,7,8])

In [43]:
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [50]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6]])

In [51]:
x

array([[1, 2],
       [3, 4]])

In [52]:
y

array([[5, 6]])

In [53]:
np.concatenate((x,y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [57]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [58]:
array_example

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [59]:
array_example.ndim

3

In [74]:
b = np.array([[1,2,3,5],[2,3,4,6],[4,5,6,7]])

In [75]:
b

array([[1, 2, 3, 5],
       [2, 3, 4, 6],
       [4, 5, 6, 7]])

In [76]:
b.ndim

2

In [79]:
b.shape

(3, 4)

In [77]:
array_example.size

24

In [78]:
array_example.shape

(3, 2, 4)

In [80]:
a = np.arange(6)

In [81]:
a

array([0, 1, 2, 3, 4, 5])

In [85]:
a.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [86]:
np.reshape(a, newshape=(1,6), order="C")

array([[0, 1, 2, 3, 4, 5]])

In [87]:
a = np.array([1, 2, 3, 4, 5, 6])

In [88]:
a.shape

(6,)

In [89]:
a2 = a[np.newaxis, :]

In [90]:
a2

array([[1, 2, 3, 4, 5, 6]])

In [92]:
a2.shape

(1, 6)

In [93]:
a[:,np.newaxis]

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [94]:
data = np.array([1,2,3])

In [95]:
data

array([1, 2, 3])

In [97]:
data[0:2]

array([1, 2])

In [98]:
data[1:]

array([2, 3])

In [99]:
data[-2:]

array([2, 3])

In [100]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [101]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [103]:
a[a < 5]

array([1, 2, 3, 4])

In [104]:
a[a >= 5]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [106]:
a[a%2 == 0]

array([ 2,  4,  6,  8, 10, 12])

In [107]:
a[(a > 2) & (a < 11)]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [109]:
a[(a > 5) | (a == 5)]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [111]:
b = np.nonzero(a < 5)

In [112]:
b

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))

In [114]:
list(zip(b[0],b[1]))

[(0, 0), (0, 1), (0, 2), (0, 3)]

In [115]:
list_of_coordinates= list(zip(b[0], b[1]))

In [116]:
list_of_coordinates

[(0, 0), (0, 1), (0, 2), (0, 3)]

In [117]:
for coord in list_of_coordinates :
    print (coord)

(0, 0)
(0, 1)
(0, 2)
(0, 3)


In [118]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [119]:
arr1 = a[3 : 8]

In [120]:
arr1

array([4, 5, 6, 7, 8])

In [121]:
a1 = np.array([[1, 1],
               [2, 2]])

In [122]:
a2 = np.array([[3, 3],
               [4, 4]])

In [123]:
a1

array([[1, 1],
       [2, 2]])

In [124]:
a2

array([[3, 3],
       [4, 4]])

In [129]:
np.concatenate((a1,a2), axis = 1)

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [130]:
np.vstack((a1,a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [132]:
a = np.arange(1,15)

In [133]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [134]:
np.arange(1,15).reshape(2,7)

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [135]:
x = np.arange(1, 25).reshape(2, 12)

In [136]:
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [141]:
np.hsplit(x,(3,6,8))

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4,  5,  6],
        [16, 17, 18]]),
 array([[ 7,  8],
        [19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [164]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [165]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [166]:
b1 = a[0,:].copy()

In [167]:
b1

array([1, 2, 3, 4])

In [168]:
b1[0] = 99

In [169]:
b1

array([99,  2,  3,  4])

In [170]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [171]:
data = np.array([1, 2])

In [172]:
ones = np.ones(2, dtype=int)

In [173]:
data

array([1, 2])

In [174]:
ones

array([1, 1])

In [176]:
data + ones

array([2, 3])

In [177]:
a = np.array([1,2,3,4])

In [178]:
a

array([1, 2, 3, 4])

In [179]:
a.sum()

10

In [180]:
b = np.array([[1, 1], [2, 2]])

In [181]:
b

array([[1, 1],
       [2, 2]])

In [182]:
b.sum(axis=0)

array([3, 3])

In [183]:
b.sum(axis=1)

array([2, 4])

In [184]:
b

array([[1, 1],
       [2, 2]])

In [185]:
b = np.array([[1, 4], [2, 7]])

In [186]:
b

array([[1, 4],
       [2, 7]])

In [187]:
b.min(axis=0)

array([1, 4])

In [188]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [189]:
a.min(axis=0)

array([0.12697628, 0.05093587, 0.26590556, 0.5510652 ])

In [190]:
a.max(axis=0)

array([0.54627315, 0.82485143, 0.40067661, 0.56917101])

In [191]:
data = np.array([[1, 2], [3, 4], [5, 6]])

In [192]:
data[0,1]

2

In [193]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [195]:
data[0:2,0]

array([1, 3])

In [197]:
data[0,0:2]

array([1, 2])

In [201]:
data.max(axis=1)

array([2, 4, 6])

In [202]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [206]:
np.unique(a, return_index=True)

(array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20]),
 array([ 0,  2,  3,  4,  5,  6,  7, 12, 13, 14]))